[package]
name = "BasicCoin"
version = "0.0.0"

[dependencies]
MoveStdlib = { local = "../../../../move-stdlib/"}
MoveNursery = { local = "../../../../move-stdlib/nursery"}

[addresses]
#any address in HEX
std = "0xABCD"